[package]
name = "test-goreleaser-rust"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
git2 = { version = "0.20.2", default-features = false }
chrono = "0.4"
